language: node_js
dist: trusty
sudo: required
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      # latest version of Firefox already installed by default
node_js:
  - 'node'
  - '8'
  - '6'
env:
  matrix:
    - SELENIUM_VERSION=2 PROTRACTOR_VERSION=4
    - SELENIUM_VERSION=3 PROTRACTOR_VERSION=5
matrix:
  exclude:
  - node_js: '8'
    env: SELENIUM_VERSION=2 PROTRACTOR_VERSION=4
  - node_js: 'node'
    env: SELENIUM_VERSION=2 PROTRACTOR_VERSION=4
before_install:
  - rm package-lock.json
install:
  - npm install selenium-webdriver@^$SELENIUM_VERSION protractor@^$PROTRACTOR_VERSION
  - npm install
  - npm install webdriver-manager
  - webdriver-manager update
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - webdriver-manager start &
  - sleep 10 # give webdriver some time to start
script:
  - node index.js
  - npm run test-selenium
  - npm run test-protractor
after_script:
  - sh -e /etc/init.d/xvfb stop
